[0m18:23:53.397916 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000265BF8990F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000265C1856800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000265C1856A10>]}


============================== 18:23:53.434153 | b3e528d4-03ba-4fe7-b796-18f9e4a368a6 ==============================
[0m18:23:53.434153 [info ] [MainThread]: Running with dbt=1.10.2
[0m18:23:53.437415 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\ayman\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init fakeschool_dbt', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m18:23:53.997582 [info ] [MainThread]: Creating dbt configuration folder at C:\Users\ayman\.dbt
[0m18:23:54.026175 [debug] [MainThread]: Starter project path: C:\Users\ayman\desktop\FakeSchoolData\venv\lib\site-packages\dbt\include\starter_project
[0m18:23:54.205764 [info ] [MainThread]: 
Your new dbt project "fakeschool_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:23:54.207953 [info ] [MainThread]: Setting up your profile.
[0m18:26:00.641984 [info ] [MainThread]: Profile fakeschool_dbt written to C:\Users\ayman\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m18:26:00.648751 [debug] [MainThread]: Command `dbt init` succeeded at 18:26:00.647252 after 127.59 seconds
[0m18:26:00.650847 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000265BF8990F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000265C1862DA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000265C1856AD0>]}
[0m18:26:00.652879 [debug] [MainThread]: Flushing usage events
[0m18:26:01.113122 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:13:24.552443 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FDD9C81150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FDDAB567D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FDDAB569B0>]}


============================== 12:13:24.626682 | 26684168-03b5-49ef-b890-2d5554d2fec2 ==============================
[0m12:13:24.626682 [info ] [MainThread]: Running with dbt=1.10.2
[0m12:13:24.630930 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\ayman\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt seed', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:13:24.633250 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\ayman\Desktop\FakeSchoolData\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:13:24.639500 [debug] [MainThread]: Command `dbt seed` failed at 12:13:24.639500 after 0.39 seconds
[0m12:13:24.642500 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FDD9C81150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FDDAB566E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FDDAB56710>]}
[0m12:13:24.644500 [debug] [MainThread]: Flushing usage events
[0m12:13:25.195586 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:14:21.175760 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000259F9195090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000259FB157130>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000259FB157310>]}


============================== 13:14:21.194165 | 498a07f1-2ce1-4714-a051-99e90699f6b2 ==============================
[0m13:14:21.194165 [info ] [MainThread]: Running with dbt=1.10.2
[0m13:14:21.198519 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\ayman\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt seed', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:14:21.200843 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\ayman\Desktop\FakeSchoolData\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:14:21.206111 [debug] [MainThread]: Command `dbt seed` failed at 13:14:21.206111 after 0.31 seconds
[0m13:14:21.209278 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000259F9195090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000259FB157040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000259FB157070>]}
[0m13:14:21.212485 [debug] [MainThread]: Flushing usage events
[0m13:14:21.777685 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:19:54.656453 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F803FB1120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F804E867D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F804E869B0>]}


============================== 13:19:54.668969 | c9c0c611-7801-4d22-afad-f1d196effcc6 ==============================
[0m13:19:54.668969 [info ] [MainThread]: Running with dbt=1.10.2
[0m13:19:54.671726 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\ayman\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt seed', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:19:54.674895 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\ayman\Desktop\FakeSchoolData\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:19:54.679130 [debug] [MainThread]: Command `dbt seed` failed at 13:19:54.679130 after 0.29 seconds
[0m13:19:54.681162 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F803FB1120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F804E866E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F804E86710>]}
[0m13:19:54.683302 [debug] [MainThread]: Flushing usage events
[0m13:19:55.136094 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:55:09.721861 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002992F4850C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000299313567D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000299313569B0>]}


============================== 13:55:09.738561 | ffb5250e-326e-4e3c-b51a-4ea7602683b8 ==============================
[0m13:55:09.738561 [info ] [MainThread]: Running with dbt=1.10.2
[0m13:55:09.742980 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\ayman\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt seed', 'send_anonymous_usage_stats': 'True'}
[0m13:55:09.746982 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\ayman\Desktop\FakeSchoolData\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:55:09.753980 [debug] [MainThread]: Command `dbt seed` failed at 13:55:09.753980 after 0.31 seconds
[0m13:55:09.757051 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002992F4850C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000299313566E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029931356710>]}
[0m13:55:09.760576 [debug] [MainThread]: Flushing usage events
[0m13:55:10.227592 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:49:14.083415 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017D9E981150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017DA085E7D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017DA085E9B0>]}


============================== 15:49:14.099452 | 34ce3695-aff2-4bd9-bbea-8ce9ff8c2853 ==============================
[0m15:49:14.099452 [info ] [MainThread]: Running with dbt=1.10.2
[0m15:49:14.101815 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\ayman\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run --select gold', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:49:14.104814 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\ayman\Desktop\FakeSchoolData\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:49:14.111214 [debug] [MainThread]: Command `dbt run` failed at 15:49:14.110217 after 0.35 seconds
[0m15:49:14.113396 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017D9E981150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017DA085E6E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017DA085E710>]}
[0m15:49:14.115396 [debug] [MainThread]: Flushing usage events
[0m15:49:14.586233 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:13:34.945848 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022473681120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002247555A7D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002247555A9B0>]}


============================== 15:13:34.981758 | 6585a395-f0e7-400b-ba4c-d3269b2c8f57 ==============================
[0m15:13:34.981758 [info ] [MainThread]: Running with dbt=1.10.2
[0m15:13:34.984309 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\ayman\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt debug --profiles-dir C:\\Users\\ayman\\.dbt', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:13:35.546457 [info ] [MainThread]: dbt version: 1.10.2
[0m15:13:35.548486 [info ] [MainThread]: python version: 3.10.11
[0m15:13:35.551520 [info ] [MainThread]: python path: C:\Users\ayman\desktop\FakeSchoolData\venv\Scripts\python.exe
[0m15:13:35.553938 [info ] [MainThread]: os info: Windows-10-10.0.26100-SP0
[0m15:13:57.939568 [info ] [MainThread]: Using profiles dir at C:\Users\ayman\.dbt
[0m15:13:57.941582 [info ] [MainThread]: Using profiles.yml file at C:\Users\ayman\.dbt\profiles.yml
[0m15:13:57.944633 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\ayman\Desktop\FakeSchoolData\dbt_project.yml
[0m15:13:57.971156 [info ] [MainThread]: adapter type: snowflake
[0m15:13:57.976161 [info ] [MainThread]: adapter version: 1.9.4
[0m15:13:57.980164 [info ] [MainThread]: Configuration:
[0m15:13:57.983252 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m15:13:57.986339 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m15:13:57.989339 [info ] [MainThread]: Required dependencies:
[0m15:13:57.993340 [debug] [MainThread]: Executing "git --help"
[0m15:13:58.137791 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m15:13:58.139800 [debug] [MainThread]: STDERR: "b''"
[0m15:13:58.143093 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m15:13:58.144518 [info ] [MainThread]: Connection:
[0m15:13:58.147734 [info ] [MainThread]:   account: FSBUSLK-FQ37572
[0m15:13:58.151776 [info ] [MainThread]:   user: Aymane17
[0m15:13:58.153827 [info ] [MainThread]:   database: FAKESCHOOL
[0m15:13:58.156895 [info ] [MainThread]:   warehouse: COMPUTE_WH
[0m15:13:58.159199 [info ] [MainThread]:   role: ACCOUNTADMIN
[0m15:13:58.162716 [info ] [MainThread]:   schema: raw
[0m15:13:58.165089 [info ] [MainThread]:   authenticator: None
[0m15:13:58.169858 [info ] [MainThread]:   oauth_client_id: None
[0m15:13:58.172227 [info ] [MainThread]:   query_tag: None
[0m15:13:58.174582 [info ] [MainThread]:   client_session_keep_alive: False
[0m15:13:58.180861 [info ] [MainThread]:   host: None
[0m15:13:58.182904 [info ] [MainThread]:   port: None
[0m15:13:58.184930 [info ] [MainThread]:   proxy_host: None
[0m15:13:58.188067 [info ] [MainThread]:   proxy_port: None
[0m15:13:58.191547 [info ] [MainThread]:   protocol: None
[0m15:13:58.195872 [info ] [MainThread]:   connect_retries: 1
[0m15:13:58.198874 [info ] [MainThread]:   connect_timeout: None
[0m15:13:58.201874 [info ] [MainThread]:   retry_on_database_errors: False
[0m15:13:58.204332 [info ] [MainThread]:   retry_all: False
[0m15:13:58.206384 [info ] [MainThread]:   insecure_mode: False
[0m15:13:58.213046 [info ] [MainThread]:   reuse_connections: True
[0m15:13:58.217048 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m15:14:00.397773 [debug] [MainThread]: Acquiring new snowflake connection 'debug'
[0m15:14:07.888337 [debug] [MainThread]: Using snowflake connection "debug"
[0m15:14:07.890721 [debug] [MainThread]: On debug: select 1 as id
[0m15:14:07.892766 [debug] [MainThread]: Opening a new connection, currently in state init
[0m15:14:11.177539 [debug] [MainThread]: Snowflake adapter: Error running SQL: select 1 as id
[0m15:14:11.179781 [debug] [MainThread]: Snowflake adapter: Rolling back transaction.
[0m15:14:11.182219 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m15:14:11.185324 [info ] [MainThread]: [31m2 checks failed:[0m
[0m15:14:11.187430 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\ayman\Desktop\FakeSchoolData\dbt_project.yml> not found

[0m15:14:11.191064 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  250001 (08001): Failed to connect to DB: FSBUSLK-FQ37572.snowflakecomputing.com:443. Incorrect username or password was specified.

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m15:14:11.195718 [debug] [MainThread]: Command `dbt debug` failed at 15:14:11.195718 after 36.53 seconds
[0m15:14:11.198908 [debug] [MainThread]: Connection 'debug' was left open.
[0m15:14:11.201161 [debug] [MainThread]: On debug: No close available on handle
[0m15:14:11.204390 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022473681120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022404F3CBE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022404F3E710>]}
[0m15:14:11.207537 [debug] [MainThread]: Flushing usage events
[0m15:14:11.658057 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:14:59.785312 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025552BA10F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025553A76800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025553A769E0>]}


============================== 15:14:59.797666 | 2abfafa0-97fd-4011-87bc-c15f380de349 ==============================
[0m15:14:59.797666 [info ] [MainThread]: Running with dbt=1.10.2
[0m15:14:59.801412 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\ayman\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:14:59.804464 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\ayman\Desktop\FakeSchoolData\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:14:59.808553 [debug] [MainThread]: Command `dbt run` failed at 15:14:59.808553 after 0.32 seconds
[0m15:14:59.811093 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025552BA10F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025553A76710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025553A76740>]}
[0m15:14:59.813141 [debug] [MainThread]: Flushing usage events
[0m15:15:00.302291 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:17:12.118201 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A95C9AD180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A95E95ECE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A95E95EEC0>]}


============================== 15:17:12.131507 | 0b6d7433-17ab-4567-92af-eee7112d8259 ==============================
[0m15:17:12.131507 [info ] [MainThread]: Running with dbt=1.10.2
[0m15:17:12.136632 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\ayman\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt run-operation debug_account --profiles-dir C:\\Users\\ayman\\.dbt', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:17:12.139670 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\ayman\Desktop\FakeSchoolData\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:17:12.144213 [debug] [MainThread]: Command `dbt run-operation` failed at 15:17:12.143206 after 0.32 seconds
[0m15:17:12.145470 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A95C9AD180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A95E95EBF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A95E95EC20>]}
[0m15:17:12.149612 [debug] [MainThread]: Flushing usage events
[0m15:17:15.894082 [debug] [MainThread]: An error was encountered while trying to flush usage events
